version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - discovery.type=single-node
    volumes:
      - dataVolume:/usr/share/elasticsearch/data

  shared-content-initiative:
    build: .
    ports:
      - 5423:5423
    environment:
      - NODE_ENV=${NODE_ENV-production}
      - HOSTNAME=${HOSTNAME-localhost}
      - PORT=5423
      - TTL_DAYS=$TTL_DAYS
      - DATABASE_HOST=elasticsearch:9200
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 127.0.0.1:5601:5601
    links:
      - elasticsearch

volumes:
  dataVolume: {}
