version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - dataVolume:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601

volumes:
  dataVolume: {}
